development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: interapptive_development
  pool: 5
  username: root
  password:

production:
  host: beta.authorly.com
  username: rails
  password: f406aa0910719f5fa7f4b96f8e4faf2a
  database: authorly_production
  adapter: mysql2
  reconnect: true
  pool: 100
  encoding: utf8
